version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - docker build -t youtube:latest .
      - docker tag youtube:latest 594191747397.dkr.ecr.us-east-1.amazonaws.com/youtube
  post_build:
    commands:
      - docker push 594191747397.dkr.ecr.us-east-1.amazonaws.com/youtube
      - printf '[{"name":HelloWorld,"imageUri":"%s"}]' 594191747397.dkr.ecr.us-east-1.amazonaws.com/youtube > imagedefinitions.json
artifacts:
  files: imagedefinitions.json